// src/app/api/auth/[...nextauth]/route.ts

/**
 * NextAuth.js API Route Handler
 * * This file dynamically handles all API requests for NextAuth.js.
 * It's crucial for authentication flows, including sign-in, sign-out,
 * session management, and OAuth callbacks.
 */

// Define the runtime environment for the Vercel/Next.js environment.
// 'nodejs' is typically used for server-side logic that interacts with databases or external APIs.
export const runtime = "nodejs";

// Import the 'handlers' object generated by your NextAuth configuration file.
// This object contains the configured GET and POST functions.
import { handlers } from "@/auth";

// Destructure and export the GET and POST methods from the handlers.
// Next.js automatically maps these exports to the corresponding HTTP methods
// for any request made to the /api/auth/* path.
export const { GET, POST } = handlers;
